# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-06 09:54
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'annotations', '0001_initial'), (b'annotations', '0002_auto_20160415_1727'), (b'annotations', '0003_add_empty_labelset'), (b'annotations', '0004_alter_specify_on_delete'), (b'annotations', '0005_remove_empty_labelset'), (b'annotations', '0006_update_label_thumbnail_filepaths'), (b'annotations', '0007_color_setting_typo_fix'), (b'annotations', '0008_rename_vision_backend_fields'), (b'annotations', '0009_rename_labelgroup_table'), (b'annotations', '0010_alter_label_group_foreignkey'), (b'annotations', '0011_delete_labelgroup'), (b'annotations', '0012_rename_label_table'), (b'annotations', '0013_alter_annotation_label_foreignkey'), (b'annotations', '0014_delete_label'), (b'annotations', '0015_rename_labelset_table'), (b'annotations', '0016_delete_labelset'), (b'annotations', '0017_tool_settings_one_to_one'), (b'annotations', '0018_annotation_point_one_to_one')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0003_alter_source_labelset_null'),
        ('images', '0014_alter_source_labelset_foreignkey'),
        ('vision_backend', '__first__'),
        ('labels', '0001_initial'),
        ('labels', '0002_label'),
        ('vision_backend', '0003_alter_score_label_foreignkey'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_date', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='images.Image')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labels.Label')),
                ('point', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='images.Point')),
                ('robot_version', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vision_backend.Classifier')),
                ('source', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='images.Source')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationToolAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_date', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='images.Image')),
                ('source', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='images.Source')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationToolSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_marker', models.CharField(choices=[(b'crosshair', b'Crosshair'), (b'circle', b'Circle'), (b'crosshair and circle', b'Crosshair and circle'), (b'box', b'Box')], default=b'crosshair', max_length=30)),
                ('point_marker_size', models.IntegerField(default=16, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('point_marker_is_scaled', models.BooleanField(default=False)),
                ('point_number_size', models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('point_number_is_scaled', models.BooleanField(default=False)),
                ('unannotated_point_color', models.CharField(default=b'FFFF00', max_length=6, verbose_name=b'Not annotated point color')),
                ('robot_annotated_point_color', models.CharField(default=b'FFFF00', max_length=6, verbose_name=b'Unconfirmed point color')),
                ('human_annotated_point_color', models.CharField(default=b'8888FF', max_length=6, verbose_name=b'Confirmed point color')),
                ('selected_point_color', models.CharField(default=b'00FF00', max_length=6)),
                ('show_machine_annotations', models.BooleanField(default=True)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
