# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-06 20:08
from __future__ import unicode_literals

from django.db import migrations


def populate_features_image(apps, schema_editor):
    # Populate the Features model's image_new field using the Image.features
    # value.
    Image = apps.get_model('image', 'Image')
    for img in Image.objects.all():
        if img.features:
            img.features.image_new = img
            img.features.save()


def populate_image_features(apps, schema_editor):
    # Populate the Image model's features field using the Features.image_new
    # value (reverse relation is features_new).
    Image = apps.get_model('image', 'Image')
    for img in Image.objects.all():
        if img.features_new:
            img.features = img.features_new
            img.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0006_features_add_image_field'),
    ]

    operations = [
        migrations.RunPython(
            populate_features_image, populate_image_features, elidable=True),
    ]
