# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-06 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0023_remove_image_features'),
        ('vision_backend', '0007_features_populate_image_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features', old_name='image_new', new_name='image',
        ),
        # Remove custom related_name, now that the default won't cause conflicts
        migrations.AlterField(
            model_name='features',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
        ),
    ]
