# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-06 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0008_rename_features_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
        ),
    ]
